name: API Integration Tests
on: [push]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: start mongo
        run: |
          docker compose -f mongo.yml up -d
      - name: Wait for Mongo
        run: sleep 10
      - name: Start flask
        run: |
          export FLASK_APP=app/api.py
          export PYTHONPATH=$GITHUB_WORKSPACE
          flask run &
          sleep 5
      - name: Execute API tests
        run: |
          python3 -m pytest tests/api